version: "3.3"



services:

  nginx:
    image: alimizan/todo-nginx:latest
    ports:
      - 80:80
    container_name: nginx

  todo:
    image: alimizan/react-todo-app:latest
    ports:
      - 3000:3000
    container_name: todo

